### ISSUE TITLE
Extract app informations from AppImage

### ISSUE THREAD

**Issue by francesco-gaglione** [francesco-gaglione/AppHub#30]
It is possible to extract app informations from the AppImage file using 

```bash
./appName.AppImage --appimage-extract
```
This will help the user since he don't have to find and download an icon from the internet, same as app name, version and so on.

**Comment by ivan-hc** [comment]
Ciao, this is the workflow I use in my package manager to extract launcher and icon
```
# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract *.desktop 1>/dev/null
./$APP --appimage-extract share/applications/*.desktop 1>/dev/null
./$APP --appimage-extract usr/share/applications/*.desktop 1>/dev/null
mv squashfs-root/*.desktop ./$APP.desktop
mv squashfs-root/share/applications/*.desktop ./$APP.desktop
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$app*.desktop 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$app*.desktop 1>/dev/null
	mv squashfs-root/share/applications/*.desktop ./$APP.desktop
fi
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
sed -i "s#AppRun#$APP#g" ./$APP.desktop
sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop
sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop

mkdir icons
mv $(./$APP --appimage-extract *.png) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract *.svg) ./icons/$APP 2>/dev/null
./$APP --appimage-extract share/icons/*/*/* 1>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/* 1>/dev/null
./$APP --appimage-extract share/icons/*/*/*/* 1>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/*/* 1>/dev/null
mv ./squashfs-root/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
```
from this template https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage

buona serata

**Comment by francesco-gaglione** [comment]
@ivan-hc  Ciao. Great I am taking a look at it and will take a cue from this template. However, your project looks very interesting and perhaps is in line with what the AppHub roadmap may be. I will consider it as an evolutionary one in future releases.

**Comment by ivan-hc** [comment]
> @ivan-hc However, your project looks very interesting and perhaps is in line with what the AppHub roadmap may be. I will consider it as an evolutionary one in future releases.

in effetti è da un paio di anni che mi propongono di utilizzare una GUI, ma ho scarsa conoscenza in merito, so solo "giocare" con BASH (non sono uno sviluppatore professionista).

Se davvero sarai interessato a implementarlo in futuro, sarebbe un insieme di elementi di manifattura al 100% italiana, e sarebbe grandioso.

**Comment by francesco-gaglione** [comment]
@ivan-hc assolutamente! Nel dettaglio è molto interessante quella sorta di database che hai nel tuo progetto.. la mia idea di roadmap per AppHub era quella di creare un vero e proprio app store (per il momento solo di AppImages dato che al momento non ne ho mai visto uno) e il tuo progetto risolve il problema piu grande... avere un "database" senza avere un servizio/backend/repository. 

Sto pensando a come costruire una serie di task in roadmap per arrivare a questo. Appena ho un'idea ti pinghero sicuramente

**Comment by ivan-hc** [comment]
Ho anche provveduto a un catalogo:

https://portable-linux-apps.github.io

però è da notare che non distribuisco solo AppImage. Ci sono una quarantina/cinquantina di programmi standalone o script. Io stesso uso la versione TAR di Firefox, per intenderci.

> @ivan-hc assolutamente! Nel dettaglio è molto interessante quella sorta di database che hai nel tuo progetto.. la mia idea di roadmap per AppHub era quella di creare un vero e proprio app store (per il momento solo di AppImages dato che al momento non ne ho mai visto uno) e il tuo progetto risolve il problema piu grande... avere un "database" senza avere un servizio/backend/repository.

lo so, il fatto è che il creatore in persona del formato AppImage, Peter Simons, è sempre stato contrario ai gestori di pacchetti, secondo lui "chi ne ha mai avuto bisogno?", in pieno stile Windows e macOS. Ecco perché il mio progetto non è tanto pubblicizzato. Ho solo una recensione (sbagliata) da parte di DistroTube, su YouTube (usava una versione vecchia di un anno, con tanto di problemi a essa legata, per cui sul finire del video si è anche trovato impacciato, vedere https://www.youtube.com/watch?v=7SfDlR3vU3I ).

Sono tre anni che mi batto per far riacquisire credibilità nel formato di packaging AppImage, tant'è che ne ho creati una sessantina, sparsi tra i miei repository, e uso script miei per crearne https://github.com/ivan-hc#creating-appimage-packages
ma gli autosabotaggi dell'autore sono quelli che passano più all'occhio, tant'è che molti sviluppatori lo hanno schifato, preferendo Flatpak. Ho anche creato una versione non ufficiale di [Bottles](https://github.com/ivan-hc/Bottles-appimage), per intenderci, grazie anche ai consigli di Mirko Brombin, lo sviluppatore, italiano anche lui.

**Comment by ivan-hc** [comment]
Nel frattempo, ho aggiunto la tua app al database https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/44850637bec7fd26815df4ae967f877607c4dd80
