### ISSUE TITLE
Settings wants superuser priveleges to change user settings & fails

### ISSUE THREAD

**Issue by jelabarre59** [francesco-gaglione/AppHub#47]
Opening the AppHub settings, under Advanced, I am trying to change my user's Appimage directory.

The default is showing the AppImages directory in my home directory.  I will change the directory to the new location (also in my home directory) and when I try to Save the settings, I get a policykit window with

`Authentication is needed to run '/usr/bin/app_hub_backend --action upda ... install-dir /home/jlabarre/AppImages/' as the super user`

I have tried my own user password (whuch has sudo privileges) as well as the system root password.  The dialog will not accept either password, and the only option is to cancel the process.

Fedora 40, x86_64
app-hub-0.1.1-1.x86_64.rpm
Cinnamon Desktop

**Comment by francesco-gaglione** [comment]
The super user permissions are needed since the app has to update .desktop files that are located in a protected directory. 
The issue seems to be a non-existent path at first installation. I'm working on it and I'll release a fix.
Thank you for your feedback!!

**Comment by francesco-gaglione** [comment]
@jelabarre59 new release v0.1.2 include this fix, let me know if I can close the issue

**Comment by jelabarre59** [comment]
Well, that doesn't work for my use case, so I've removed the application.

**Comment by francesco-gaglione** [comment]
@jelabarre59 now should work and with the new v.0.2 beta release there is a sort of marketplace so new feature!
Let us know in the meantime I close the issue, tested the changes and they work in my test environment.
